name: Deploy blog site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          
      - uses: actions/checkout@v3      

      - name: Install all dependencies
        run: npm install

      - name: Build Site
        run: npm run build

      - name: Deploy Site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: blog
          publish_dir: ./dist
